'use strict';


/**
 * 房主行为
 */

module.exports = {
  OVER_GAME:'OVER_GAME',
  START_GAME:'START_GAME',
  PAUSE_GAME:'PAUSE_GAME',
  RESUME_GAME:'RESUME_GAME',
  PUSH_STAGE:'PUSH_STAGE',
  SEND_ENDING:'SEND_ENDING',
};